export type Kind = 'personale' | 'piva'
export type Income = { id:string; date:string; description:string; amount:number; kind:Kind; accountId?:string; recurring?:boolean }
export type Expense = Income & { category:string }
export type Account = { id:string; name:string; type:'conto'|'carta'; balance:number; limit:number }
export type Category = { id:string; name:string; budget:number }
export type Asset = { id:string; name:string; type:'investimento'|'polizza'; paid:number; value:number }
export type Deadline = { id:string; title:string; date:string; amount:number; paid:boolean; priority:'alta'|'media'|'bassa' }
export type TaxProfile = { name:string; ateco:string; profitability:number; substituteTax:number; contributions:number; taxReserve:number }
export type BudgetState = { version:number; profile:TaxProfile; incomes:Income[]; expenses:Expense[]; accounts:Account[]; categories:Category[]; assets:Asset[]; deadlines:Deadline[] }
const year=new Date().getFullYear(); const d=(m:number,n:number)=>`${year}-${String(m).padStart(2,'0')}-${String(n).padStart(2,'0')}`
export const demoState:BudgetState={version:2,profile:{name:'Andrea Rossi',ateco:'62.01.00',profitability:67,substituteTax:5,contributions:26.07,taxReserve:35},accounts:[{id:'a1',name:'Conto principale',type:'conto',balance:12840,limit:0},{id:'a2',name:'Carta Gold',type:'carta',balance:-740,limit:3000},{id:'a3',name:'Conto P.IVA',type:'conto',balance:6250,limit:0}],categories:[{id:'c1',name:'Casa',budget:1000},{id:'c2',name:'Alimentari',budget:450},{id:'c3',name:'Mobilità',budget:300},{id:'c4',name:'Software',budget:180},{id:'c5',name:'Servizi',budget:250},{id:'c6',name:'Professionisti',budget:500}],assets:[{id:'as1',name:'ETF Piano futuro',type:'investimento',paid:8200,value:9140},{id:'as2',name:'Fondo pensione',type:'polizza',paid:4200,value:4380}],deadlines:[{id:'d1',title:'Acconto INPS',date:d(6,30),amount:1680,paid:false,priority:'alta'},{id:'d2',title:'Assicurazione auto',date:d(7,12),amount:620,paid:false,priority:'media'},{id:'d3',title:'Rinnovo dominio',date:d(8,2),amount:42,paid:false,priority:'bassa'}],incomes:[['i1',1,12,'Stipendio',2200,'personale','a1'],['i2',1,24,'Sito web — Studio Forma',1800,'piva','a3'],['i3',2,12,'Stipendio',2200,'personale','a1'],['i4',2,27,'Consulenza prodotto',2450,'piva','a3'],['i5',3,12,'Stipendio',2200,'personale','a1'],['i6',4,29,'Consulenza UX',2100,'piva','a3'],['i7',5,12,'Stipendio',2200,'personale','a1']].map(x=>({id:String(x[0]),date:d(Number(x[1]),Number(x[2])),description:String(x[3]),amount:Number(x[4]),kind:x[5] as Kind,accountId:String(x[6])})),expenses:[['e1',1,5,'Affitto',780,'personale','Casa'],['e2',1,18,'Adobe Creative Cloud',67,'piva','Software'],['e3',2,5,'Affitto',780,'personale','Casa'],['e4',2,14,'Spesa alimentare',284,'personale','Alimentari'],['e5',3,5,'Affitto',780,'personale','Casa'],['e6',3,16,'Hosting e domini',129,'piva','Servizi'],['e7',4,20,'Trasporti',176,'personale','Mobilità'],['e8',5,22,'Commercialista',420,'piva','Professionisti']].map(x=>({id:String(x[0]),date:d(Number(x[1]),Number(x[2])),description:String(x[3]),amount:Number(x[4]),kind:x[5] as Kind,category:String(x[6]),accountId:x[5]==='piva'?'a3':'a1'}))}
export const money=new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR',maximumFractionDigits:0}); export const dateIt=(v:string)=>new Intl.DateTimeFormat('it-IT',{day:'2-digit',month:'short'}).format(new Date(`${v}T12:00:00`)); export const uid=()=>crypto.randomUUID()
export function migrate(v:Partial<BudgetState>):BudgetState{return {...demoState,...v,version:2,profile:{...demoState.profile,...v.profile},accounts:v.accounts||demoState.accounts,categories:v.categories||demoState.categories,assets:v.assets||demoState.assets,deadlines:v.deadlines||demoState.deadlines}}
export function totals(s:BudgetState,y:number){const incomes=s.incomes.filter(i=>new Date(i.date).getFullYear()===y),expenses=s.expenses.filter(i=>new Date(i.date).getFullYear()===y),sum=(a:{amount:number}[])=>a.reduce((n,x)=>n+x.amount,0),pivaIncome=sum(incomes.filter(i=>i.kind==='piva')),taxable=pivaIncome*s.profile.profitability/100,contributions=taxable*s.profile.contributions/100,tax=Math.max(0,taxable-contributions)*s.profile.substituteTax/100,reserve=pivaIncome*s.profile.taxReserve/100,totalIncome=sum(incomes),totalExpense=sum(expenses),liquidity=s.accounts.reduce((n,a)=>n+a.balance,0),assets=s.assets.reduce((n,a)=>n+a.value,0);return{incomes,expenses,pivaIncome,taxable,contributions,tax,reserve,totalIncome,totalExpense,available:totalIncome-totalExpense-reserve,liquidity,assets,netWorth:liquidity+assets}}
export function monthlyData(s:BudgetState,y:number){return ['Gen','Feb','Mar','Apr','Mag','Giu','Lug','Ago','Set','Ott','Nov','Dic'].map((month,index)=>({month,entrate:s.incomes.filter(i=>new Date(i.date).getFullYear()===y&&new Date(i.date).getMonth()===index).reduce((n,x)=>n+x.amount,0),spese:s.expenses.filter(i=>new Date(i.date).getFullYear()===y&&new Date(i.date).getMonth()===index).reduce((n,x)=>n+x.amount,0)}))}
